import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        // COMPLETED BOOKINGS (10) - Nov-Dec 2024
        {
            customerId: 'user_u1v2w3x4',
            salonId: 1,
            serviceId: 1,
            staffId: 1,
            bookingDate: '2024-11-15',
            startTime: '10:00',
            endTime: '11:00',
            status: 'completed',
            notes: 'Regular customer, prefers quiet service',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            customerId: 'user_y5z6a7b8',
            salonId: 2,
            serviceId: 5,
            staffId: 4,
            bookingDate: '2024-11-20',
            startTime: '14:30',
            endTime: '16:30',
            status: 'completed',
            notes: 'First time customer',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            customerId: 'user_c9d0e1f2',
            salonId: 3,
            serviceId: 9,
            staffId: 7,
            bookingDate: '2024-11-25',
            startTime: '11:00',
            endTime: '11:45',
            status: 'completed',
            notes: null,
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            customerId: 'user_g3h4i5j6',
            salonId: 1,
            serviceId: 3,
            staffId: 2,
            bookingDate: '2024-12-01',
            startTime: '09:00',
            endTime: '10:30',
            status: 'completed',
            notes: 'Requested early morning slot',
            createdAt: new Date('2024-11-28').toISOString(),
        },
        {
            customerId: 'user_k7l8m9n0',
            salonId: 4,
            serviceId: 13,
            staffId: 10,
            bookingDate: '2024-12-05',
            startTime: '15:00',
            endTime: '15:30',
            status: 'completed',
            notes: 'Regular trim, no styling',
            createdAt: new Date('2024-12-03').toISOString(),
        },
        {
            customerId: 'user_o1p2q3r4',
            salonId: 5,
            serviceId: 17,
            staffId: 13,
            bookingDate: '2024-12-10',
            startTime: '16:00',
            endTime: '18:00',
            status: 'completed',
            notes: 'Wedding preparation service',
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            customerId: 'user_s5t6u7v8',
            salonId: 2,
            serviceId: 7,
            staffId: 5,
            bookingDate: '2024-12-12',
            startTime: '10:30',
            endTime: '11:30',
            status: 'completed',
            notes: null,
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            customerId: 'user_w9x0y1z2',
            salonId: 3,
            serviceId: 11,
            staffId: 8,
            bookingDate: '2024-12-15',
            startTime: '13:00',
            endTime: '14:00',
            status: 'completed',
            notes: 'Sensitive skin, use hypoallergenic products',
            createdAt: new Date('2024-12-12').toISOString(),
        },
        {
            customerId: 'user_a3b4c5d6',
            salonId: 4,
            serviceId: 15,
            staffId: 11,
            bookingDate: '2024-12-18',
            startTime: '11:00',
            endTime: '11:45',
            status: 'completed',
            notes: 'Beard trim and shaping',
            createdAt: new Date('2024-12-15').toISOString(),
        },
        {
            customerId: 'user_e7f8g9h0',
            salonId: 1,
            serviceId: 2,
            staffId: 1,
            bookingDate: '2024-12-20',
            startTime: '14:00',
            endTime: '15:30',
            status: 'completed',
            notes: 'Holiday special occasion',
            createdAt: new Date('2024-12-18').toISOString(),
        },
        // CONFIRMED BOOKINGS (8) - Jan 20 - Feb 10, 2025
        {
            customerId: 'user_i1j2k3l4',
            salonId: 5,
            serviceId: 18,
            staffId: 14,
            bookingDate: '2025-01-22',
            startTime: '10:00',
            endTime: '11:00',
            status: 'confirmed',
            notes: 'New Year fresh look',
            createdAt: new Date('2025-01-15').toISOString(),
        },
        {
            customerId: 'user_m5n6o7p8',
            salonId: 2,
            serviceId: 6,
            staffId: 4,
            bookingDate: '2025-01-25',
            startTime: '15:30',
            endTime: '17:00',
            status: 'confirmed',
            notes: 'Special event preparation',
            createdAt: new Date('2025-01-18').toISOString(),
        },
        {
            customerId: 'user_q9r0s1t2',
            salonId: 3,
            serviceId: 10,
            staffId: 7,
            bookingDate: '2025-01-28',
            startTime: '09:30',
            endTime: '10:15',
            status: 'confirmed',
            notes: null,
            createdAt: new Date('2025-01-20').toISOString(),
        },
        {
            customerId: 'user_u3v4w5x6',
            salonId: 1,
            serviceId: 4,
            staffId: 3,
            bookingDate: '2025-02-01',
            startTime: '11:00',
            endTime: '12:30',
            status: 'confirmed',
            notes: 'Color consultation included',
            createdAt: new Date('2025-01-22').toISOString(),
        },
        {
            customerId: 'user_y7z8a9b0',
            salonId: 4,
            serviceId: 14,
            staffId: 10,
            bookingDate: '2025-02-03',
            startTime: '16:00',
            endTime: '16:30',
            status: 'confirmed',
            notes: 'Quick trim before business trip',
            createdAt: new Date('2025-01-25').toISOString(),
        },
        {
            customerId: 'user_c1d2e3f4',
            salonId: 5,
            serviceId: 19,
            staffId: 15,
            bookingDate: '2025-02-05',
            startTime: '13:00',
            endTime: '14:00',
            status: 'confirmed',
            notes: 'Anniversary preparation',
            createdAt: new Date('2025-01-28').toISOString(),
        },
        {
            customerId: 'user_g5h6i7j8',
            salonId: 2,
            serviceId: 8,
            staffId: 6,
            bookingDate: '2025-02-08',
            startTime: '10:30',
            endTime: '11:30',
            status: 'confirmed',
            notes: 'Full service package',
            createdAt: new Date('2025-02-01').toISOString(),
        },
        {
            customerId: 'user_k9l0m1n2',
            salonId: 3,
            serviceId: 12,
            staffId: 9,
            bookingDate: '2025-02-10',
            startTime: '14:00',
            endTime: '15:30',
            status: 'confirmed',
            notes: 'Monthly maintenance appointment',
            createdAt: new Date('2025-02-03').toISOString(),
        },
        // PENDING BOOKINGS (7) - Jan 18-27, 2025
        {
            customerId: 'user_o3p4q5r6',
            salonId: 1,
            serviceId: 1,
            staffId: 1,
            bookingDate: '2025-01-20',
            startTime: '10:00',
            endTime: '11:00',
            status: 'pending',
            notes: 'Waiting for confirmation',
            createdAt: new Date('2025-01-18').toISOString(),
        },
        {
            customerId: 'user_s7t8u9v0',
            salonId: 4,
            serviceId: 16,
            staffId: 12,
            bookingDate: '2025-01-21',
            startTime: '15:00',
            endTime: '16:00',
            status: 'pending',
            notes: null,
            createdAt: new Date('2025-01-19').toISOString(),
        },
        {
            customerId: 'user_u1v2w3x4',
            salonId: 5,
            serviceId: 20,
            staffId: 15,
            bookingDate: '2025-01-23',
            startTime: '11:30',
            endTime: '12:30',
            status: 'pending',
            notes: 'Flexible with timing',
            createdAt: new Date('2025-01-20').toISOString(),
        },
        {
            customerId: 'user_y5z6a7b8',
            salonId: 2,
            serviceId: 5,
            staffId: 4,
            bookingDate: '2025-01-24',
            startTime: '09:00',
            endTime: '11:00',
            status: 'pending',
            notes: 'Early morning preferred',
            createdAt: new Date('2025-01-21').toISOString(),
        },
        {
            customerId: 'user_c9d0e1f2',
            salonId: 3,
            serviceId: 9,
            staffId: 7,
            bookingDate: '2025-01-25',
            startTime: '14:30',
            endTime: '15:15',
            status: 'pending',
            notes: 'Same stylist as last time',
            createdAt: new Date('2025-01-22').toISOString(),
        },
        {
            customerId: 'user_g3h4i5j6',
            salonId: 1,
            serviceId: 3,
            staffId: 2,
            bookingDate: '2025-01-26',
            startTime: '16:00',
            endTime: '17:30',
            status: 'pending',
            notes: 'After work appointment',
            createdAt: new Date('2025-01-23').toISOString(),
        },
        {
            customerId: 'user_k7l8m9n0',
            salonId: 4,
            serviceId: 13,
            staffId: 10,
            bookingDate: '2025-01-27',
            startTime: '12:00',
            endTime: '12:30',
            status: 'pending',
            notes: 'Lunch break appointment',
            createdAt: new Date('2025-01-24').toISOString(),
        },
        // CANCELLED BOOKINGS (5) - Mix of dates
        {
            customerId: 'user_o1p2q3r4',
            salonId: 2,
            serviceId: 7,
            staffId: 5,
            bookingDate: '2024-11-28',
            startTime: '10:00',
            endTime: '11:00',
            status: 'cancelled',
            notes: 'Customer requested cancellation - schedule conflict',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            customerId: 'user_s5t6u7v8',
            salonId: 5,
            serviceId: 17,
            staffId: 13,
            bookingDate: '2024-12-08',
            startTime: '13:00',
            endTime: '15:00',
            status: 'cancelled',
            notes: 'Cancelled due to illness',
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            customerId: 'user_w9x0y1z2',
            salonId: 3,
            serviceId: 11,
            staffId: 8,
            bookingDate: '2024-12-22',
            startTime: '15:30',
            endTime: '16:30',
            status: 'cancelled',
            notes: 'Travel plans changed',
            createdAt: new Date('2024-12-15').toISOString(),
        },
        {
            customerId: 'user_a3b4c5d6',
            salonId: 1,
            serviceId: 2,
            staffId: 1,
            bookingDate: '2025-01-18',
            startTime: '11:00',
            endTime: '12:30',
            status: 'cancelled',
            notes: 'Customer no-show, cancelled by salon',
            createdAt: new Date('2025-01-15').toISOString(),
        },
        {
            customerId: 'user_e7f8g9h0',
            salonId: 4,
            serviceId: 15,
            staffId: 11,
            bookingDate: '2025-01-19',
            startTime: '09:30',
            endTime: '10:15',
            status: 'cancelled',
            notes: 'Rescheduled to later date',
            createdAt: new Date('2025-01-16').toISOString(),
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});