import { db } from '@/db';
import { salons } from '@/db/schema';

async function main() {
    const sampleSalons = [
        {
            ownerId: 'user_a1b2c3d4',
            name: 'Elegance Hair Studio',
            description: 'Premium hair styling and beauty services in the heart of the city',
            address: '123 Main Street, Downtown',
            city: 'Mumbai',
            latitude: 19.0760,
            longitude: 72.8777,
            phone: '+91-9876543210',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
            openingTime: '09:00',
            closingTime: '20:00',
            salonType: 'women',
            gstNumber: '27AABCU9603R1ZM',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_001.pdf',
                businessLicense: 'business_license_001.pdf',
                ownerIdProof: 'aadhar_001.pdf'
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            ownerId: 'user_a1b2c3d4',
            name: 'Urban Cuts Barbershop',
            description: 'Modern barbershop offering classic and contemporary styles',
            address: '456 Park Avenue, Suburb',
            city: 'Mumbai',
            latitude: 19.1136,
            longitude: 72.8697,
            phone: '+91-9876543211',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800',
            openingTime: '10:00',
            closingTime: '21:00',
            salonType: 'men',
            gstNumber: '27AABCU9603R1ZN',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_002.pdf',
                businessLicense: 'business_license_002.pdf',
                ownerIdProof: 'aadhar_002.pdf'
            },
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            ownerId: 'user_e5f6g7h8',
            name: 'Glamour Beauty Lounge',
            description: 'Full-service beauty salon with spa and wellness treatments',
            address: '789 Lake Road, Bandra',
            city: 'Mumbai',
            latitude: 19.0596,
            longitude: 72.8295,
            phone: '+91-9876543212',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800',
            openingTime: '08:00',
            closingTime: '22:00',
            salonType: 'women',
            gstNumber: '27AABCU9603R1ZO',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_003.pdf',
                businessLicense: 'business_license_003.pdf',
                ownerIdProof: 'aadhar_003.pdf'
            },
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            ownerId: 'user_e5f6g7h8',
            name: 'Style Hub Unisex',
            description: 'Trendy unisex salon for all your grooming needs',
            address: '321 Beach Road, Juhu',
            city: 'Mumbai',
            latitude: 19.1075,
            longitude: 72.8263,
            phone: '+91-9876543213',
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800',
            openingTime: '09:30',
            closingTime: '20:30',
            salonType: 'unisex',
            gstNumber: '27AABCU9603R1ZP',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_004.pdf',
                businessLicense: 'business_license_004.pdf',
                ownerIdProof: 'aadhar_004.pdf'
            },
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            ownerId: 'user_i9j0k1l2',
            name: 'The Barber Club',
            description: 'Exclusive mens grooming club with premium services',
            address: '654 Hill Street, Andheri',
            city: 'Mumbai',
            latitude: 19.1197,
            longitude: 72.8464,
            phone: '+91-9876543214',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800',
            openingTime: '10:00',
            closingTime: '21:00',
            salonType: 'men',
            isVerified: false,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            ownerId: 'user_i9j0k1l2',
            name: 'Radiance Beauty Spa',
            description: 'Luxurious spa and beauty treatments for modern women',
            address: '987 Garden Lane, Powai',
            city: 'Mumbai',
            latitude: 19.1176,
            longitude: 72.9060,
            phone: '+91-9876543215',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?w=800',
            openingTime: '08:30',
            closingTime: '21:30',
            salonType: 'women',
            gstNumber: '27AABCU9603R1ZQ',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_006.pdf',
                businessLicense: 'business_license_006.pdf',
                ownerIdProof: 'aadhar_006.pdf'
            },
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            ownerId: 'user_m3n4o5p6',
            name: 'Fresh Cuts Salon',
            description: 'Affordable and quality haircuts for everyone',
            address: '147 Market Street, Goregaon',
            city: 'Mumbai',
            latitude: 19.1663,
            longitude: 72.8526,
            phone: '+91-9876543216',
            rating: 4.3,
            imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800',
            openingTime: '09:00',
            closingTime: '20:00',
            salonType: 'unisex',
            isVerified: false,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            ownerId: 'user_m3n4o5p6',
            name: 'Gentleman Grooming',
            description: 'Traditional barbershop with modern techniques',
            address: '258 Station Road, Borivali',
            city: 'Mumbai',
            latitude: 19.2307,
            longitude: 72.8567,
            phone: '+91-9876543217',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800',
            openingTime: '10:00',
            closingTime: '21:00',
            salonType: 'men',
            gstNumber: '27AABCU9603R1ZR',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_008.pdf',
                businessLicense: 'business_license_008.pdf',
                ownerIdProof: 'aadhar_008.pdf'
            },
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            ownerId: 'user_q7r8s9t0',
            name: 'Trendz Unisex Salon',
            description: 'Latest hairstyles and beauty trends under one roof',
            address: '369 Mall Road, Malad',
            city: 'Mumbai',
            latitude: 19.1868,
            longitude: 72.8483,
            phone: '+91-9876543218',
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800',
            openingTime: '09:00',
            closingTime: '21:00',
            salonType: 'unisex',
            isVerified: false,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            ownerId: 'user_q7r8s9t0',
            name: 'Bliss Beauty Studio',
            description: 'Complete beauty solutions with expert stylists',
            address: '741 Tower Street, Kandivali',
            city: 'Mumbai',
            latitude: 19.2094,
            longitude: 72.8495,
            phone: '+91-9876543219',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
            openingTime: '08:00',
            closingTime: '22:00',
            salonType: 'unisex',
            gstNumber: '27AABCU9603R1ZS',
            isVerified: true,
            verificationDocuments: {
                gstCertificate: 'gst_cert_010.pdf',
                businessLicense: 'business_license_010.pdf',
                ownerIdProof: 'aadhar_010.pdf'
            },
            createdAt: new Date('2024-03-01').toISOString(),
        }
    ];

    await db.insert(salons).values(sampleSalons);
    
    console.log('✅ Salons seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});