import { db } from '@/db';
import { user } from '@/db/schema';

async function main() {
    const sampleUsers = [
        // Owner Users (5 total)
        {
            id: 'user_a1b2c3d4',
            name: 'Sarah Chen',
            email: 'sarah.chen@salonowner.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
            role: 'owner',
            phone: '+12025551001',
            gender: 'female',
            createdAt: new Date('2024-01-15T10:30:00Z'),
            updatedAt: new Date('2024-01-15T10:30:00Z'),
        },
        {
            id: 'user_e5f6g7h8',
            name: 'Michael Rodriguez',
            email: 'michael.rodriguez@salonowner.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
            role: 'owner',
            phone: '+919876543210',
            gender: 'male',
            createdAt: new Date('2024-02-20T14:15:00Z'),
            updatedAt: new Date('2024-02-20T14:15:00Z'),
        },
        {
            id: 'user_i9j0k1l2',
            name: 'Emma Johnson',
            email: 'emma.johnson@salonowner.com',
            emailVerified: true,
            image: null,
            role: 'owner',
            phone: '+442071234567',
            gender: 'female',
            createdAt: new Date('2024-03-10T09:45:00Z'),
            updatedAt: new Date('2024-03-10T09:45:00Z'),
        },
        {
            id: 'user_m3n4o5p6',
            name: 'David Kim',
            email: 'david.kim@salonowner.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
            role: 'owner',
            phone: '+12125552345',
            gender: 'male',
            createdAt: new Date('2024-04-05T11:20:00Z'),
            updatedAt: new Date('2024-04-05T11:20:00Z'),
        },
        {
            id: 'user_q7r8s9t0',
            name: 'Lisa Taylor',
            email: 'lisa.taylor@salonowner.com',
            emailVerified: false,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
            role: 'owner',
            phone: '+919123456789',
            gender: 'female',
            createdAt: new Date('2024-05-12T16:30:00Z'),
            updatedAt: new Date('2024-05-12T16:30:00Z'),
        },
        // Customer Users (20 total)
        {
            id: 'user_u1v2w3x4',
            name: 'James Anderson',
            email: 'james.anderson@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
            role: 'customer',
            phone: '+12025553456',
            gender: 'male',
            createdAt: new Date('2024-01-22T08:15:00Z'),
            updatedAt: new Date('2024-01-22T08:15:00Z'),
        },
        {
            id: 'user_y5z6a7b8',
            name: 'Priya Sharma',
            email: 'priya.sharma@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
            role: 'customer',
            phone: '+919876543211',
            gender: 'female',
            createdAt: new Date('2024-02-14T13:45:00Z'),
            updatedAt: new Date('2024-02-14T13:45:00Z'),
        },
        {
            id: 'user_c9d0e1f2',
            name: 'Robert Williams',
            email: 'robert.williams@email.com',
            emailVerified: false,
            image: null,
            role: 'customer',
            phone: '+442071234568',
            gender: 'male',
            createdAt: new Date('2024-03-08T10:30:00Z'),
            updatedAt: new Date('2024-03-08T10:30:00Z'),
        },
        {
            id: 'user_g3h4i5j6',
            name: 'Maria Garcia',
            email: 'maria.garcia@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
            role: 'customer',
            phone: '+12125554567',
            gender: 'female',
            createdAt: new Date('2024-04-17T15:20:00Z'),
            updatedAt: new Date('2024-04-17T15:20:00Z'),
        },
        {
            id: 'user_k7l8m9n0',
            name: 'Ahmed Hassan',
            email: 'ahmed.hassan@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
            role: 'customer',
            phone: '+919123456790',
            gender: 'male',
            createdAt: new Date('2024-05-23T09:00:00Z'),
            updatedAt: new Date('2024-05-23T09:00:00Z'),
        },
        {
            id: 'user_o1p2q3r4',
            name: 'Jennifer Lee',
            email: 'jennifer.lee@email.com',
            emailVerified: true,
            image: null,
            role: 'customer',
            phone: '+12025555678',
            gender: 'female',
            createdAt: new Date('2024-06-11T12:30:00Z'),
            updatedAt: new Date('2024-06-11T12:30:00Z'),
        },
        {
            id: 'user_s5t6u7v8',
            name: 'Daniel Brown',
            email: 'daniel.brown@email.com',
            emailVerified: false,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
            role: 'customer',
            phone: '+442071234569',
            gender: 'male',
            createdAt: new Date('2024-07-05T14:45:00Z'),
            updatedAt: new Date('2024-07-05T14:45:00Z'),
        },
        {
            id: 'user_w9x0y1z2',
            name: 'Aisha Patel',
            email: 'aisha.patel@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
            role: 'customer',
            phone: '+919876543212',
            gender: 'female',
            createdAt: new Date('2024-08-19T11:15:00Z'),
            updatedAt: new Date('2024-08-19T11:15:00Z'),
        },
        {
            id: 'user_a3b4c5d6',
            name: 'Christopher Davis',
            email: 'christopher.davis@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher',
            role: 'customer',
            phone: '+12125556789',
            gender: 'male',
            createdAt: new Date('2024-09-02T08:45:00Z'),
            updatedAt: new Date('2024-09-02T08:45:00Z'),
        },
        {
            id: 'user_e7f8g9h0',
            name: 'Sofia Martinez',
            email: 'sofia.martinez@email.com',
            emailVerified: false,
            image: null,
            role: 'customer',
            phone: '+12025557890',
            gender: 'female',
            createdAt: new Date('2024-09-15T16:20:00Z'),
            updatedAt: new Date('2024-09-15T16:20:00Z'),
        },
        {
            id: 'user_i1j2k3l4',
            name: 'Ryan Thompson',
            email: 'ryan.thompson@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan',
            role: 'customer',
            phone: '+442071234570',
            gender: 'male',
            createdAt: new Date('2024-10-08T10:00:00Z'),
            updatedAt: new Date('2024-10-08T10:00:00Z'),
        },
        {
            id: 'user_m5n6o7p8',
            name: 'Fatima Khan',
            email: 'fatima.khan@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
            role: 'customer',
            phone: '+919123456791',
            gender: 'female',
            createdAt: new Date('2024-10-22T13:30:00Z'),
            updatedAt: new Date('2024-10-22T13:30:00Z'),
        },
        {
            id: 'user_q9r0s1t2',
            name: 'Kevin White',
            email: 'kevin.white@email.com',
            emailVerified: true,
            image: null,
            role: 'customer',
            phone: '+12125558901',
            gender: 'male',
            createdAt: new Date('2024-11-05T09:15:00Z'),
            updatedAt: new Date('2024-11-05T09:15:00Z'),
        },
        {
            id: 'user_u3v4w5x6',
            name: 'Isabella Rodriguez',
            email: 'isabella.rodriguez@email.com',
            emailVerified: false,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
            role: 'customer',
            phone: '+12025559012',
            gender: 'female',
            createdAt: new Date('2024-11-18T14:00:00Z'),
            updatedAt: new Date('2024-11-18T14:00:00Z'),
        },
        {
            id: 'user_y7z8a9b0',
            name: 'Marcus Johnson',
            email: 'marcus.johnson@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
            role: 'customer',
            phone: '+442071234571',
            gender: 'male',
            createdAt: new Date('2024-12-01T11:45:00Z'),
            updatedAt: new Date('2024-12-01T11:45:00Z'),
        },
        {
            id: 'user_c1d2e3f4',
            name: 'Olivia Chen',
            email: 'olivia.chen@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
            role: 'customer',
            phone: '+919876543213',
            gender: 'female',
            createdAt: new Date('2024-12-10T08:30:00Z'),
            updatedAt: new Date('2024-12-10T08:30:00Z'),
        },
        {
            id: 'user_g5h6i7j8',
            name: 'Alex Rivera',
            email: 'alex.rivera@email.com',
            emailVerified: true,
            image: null,
            role: 'customer',
            phone: '+12125550123',
            gender: 'other',
            createdAt: new Date('2024-12-15T15:00:00Z'),
            updatedAt: new Date('2024-12-15T15:00:00Z'),
        },
        {
            id: 'user_k9l0m1n2',
            name: 'Nina Desai',
            email: 'nina.desai@email.com',
            emailVerified: false,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
            role: 'customer',
            phone: '+919123456792',
            gender: 'female',
            createdAt: new Date('2024-12-18T10:20:00Z'),
            updatedAt: new Date('2024-12-18T10:20:00Z'),
        },
        {
            id: 'user_o3p4q5r6',
            name: 'Thomas Wilson',
            email: 'thomas.wilson@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas',
            role: 'customer',
            phone: '+12025551234',
            gender: 'male',
            createdAt: new Date('2024-12-20T12:45:00Z'),
            updatedAt: new Date('2024-12-20T12:45:00Z'),
        },
        {
            id: 'user_s7t8u9v0',
            name: 'Maya Singh',
            email: 'maya.singh@email.com',
            emailVerified: true,
            image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya',
            role: 'customer',
            phone: '+442071234572',
            gender: 'female',
            createdAt: new Date('2024-12-22T09:30:00Z'),
            updatedAt: new Date('2024-12-22T09:30:00Z'),
        },
    ];

    await db.insert(user).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});